<a href="https://colab.research.google.com/github/reshminambiar/DW15_Assignment2-3/blob/main/Assignment_Numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
np.__version__

'1.21.6'

In [ ]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE4

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
x =np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
print(x.size) #gives the size of the array
print(x.itemsize) # gives the number of bytes(memory size) of a single element of the array

10
8


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
np.info(np.add)

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
x = np.zeros(10)
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
x = np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
x = [1,2,3,4,5]
x[::-1]

[5, 4, 3, 2, 1]

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
x = [1,2,0,0,4,0]
np.nonzero(x)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
np.random.random((3,3,3))

array([[[0.93401488, 0.00928334, 0.7189498 ],
        [0.37155234, 0.82521581, 0.55885032],
        [0.19725802, 0.98273073, 0.20844638]],

       [[0.83871268, 0.37879405, 0.53415168],
        [0.36811686, 0.63987623, 0.18465626],
        [0.97928046, 0.49230988, 0.24578944]],

       [[0.20255649, 0.59476339, 0.54549611],
        [0.79971127, 0.57697067, 0.90722578],
        [0.88588456, 0.13369943, 0.73900153]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
x = np.random.randint(10,100,(10,10))

In [ ]:
x

array([[42, 26, 64, 56, 34, 56, 99, 95, 17, 67],
       [99, 82, 81, 57, 18, 24, 27, 46, 37, 76],
       [58, 94, 36, 56, 38, 71, 96, 64, 51, 60],
       [65, 99, 40, 32, 89, 18, 73, 51, 87, 86],
       [26, 13, 89, 61, 60, 50, 77, 83, 63, 38],
       [80, 35, 11, 91, 77, 19, 21, 86, 97, 96],
       [44, 30, 30, 15, 92, 91, 20, 26, 41, 54],
       [58, 91, 53, 60, 87, 78, 87, 58, 18, 15],
       [49, 54, 32, 79, 61, 35, 42, 20, 92, 26],
       [75, 80, 15, 17, 11, 35, 59, 91, 90, 20]])

In [ ]:
np.min(x)

11

In [ ]:
np.max(x)

99

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
x = np.random.rand(30)

In [ ]:
x

array([0.60296905, 0.52494743, 0.23564766, 0.23727492, 0.37589764,
       0.9948943 , 0.59463924, 0.43199603, 0.51979372, 0.07173442,
       0.51527425, 0.54208393, 0.93185844, 0.75641582, 0.53606824,
       0.40614098, 0.22988728, 0.5484185 , 0.18594264, 0.22220604,
       0.15446832, 0.190715  , 0.23141329, 0.37757106, 0.25631671,
       0.07989531, 0.96692433, 0.22501638, 0.57892782, 0.95497965])

In [ ]:
np.mean(x)

0.4493439467794154

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
x = np.ones((6,6))
x[1:-1,1:-1] =0
x

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
x = np.ones((5,5))
np.pad(x,1,mode='constant',constant_values = 0)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
x = np.diag([1,2,3,4], k=-1)
x

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
x = np.ones((8,8))
x[::2]=0
x[::2,1::2] = 1
x[1::2,1::2]=0
x

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
x=np.arange(1,337).reshape(6,7,8)
np.where(x == 100)

(array([1]), array([5]), array([3]))

In [4]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
x = np.eye(2)
y = np.tile(x,(4,4))
y

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
x = np.random.rand(5,5)

In [ ]:
print(x,np.max(x), np.min(x))

[[0.49823993 0.14035718 0.76655763 0.09375838 0.60954078]
 [0.77995904 0.24308068 0.59946634 0.79337268 0.57597931]
 [0.22858283 0.51298239 0.14821712 0.52901326 0.7237326 ]
 [0.14255908 0.97416733 0.72449941 0.06190746 0.82216727]
 [0.49107725 0.99488247 0.83677333 0.93780663 0.17472276]] 0.994882472755748 0.06190746163608052


In [ ]:
y = (x- np.min(x))/(np.max(x) - np.min(x))

In [ ]:
y

array([[0.46767863, 0.08408555, 0.75527228, 0.03413909, 0.58697533],
       [0.76963645, 0.19418871, 0.57617715, 0.78401373, 0.55100281],
       [0.17864934, 0.48348018, 0.09251015, 0.50066271, 0.7093707 ],
       [0.08644564, 0.97779668, 0.7101926 , 0.        , 0.81487693],
       [0.46000138, 1.        , 0.83053228, 0.93882383, 0.12091995]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
x1 = np.arange(1,16).reshape(5,3)
x2 = np.arange(1,7).reshape(3,2)
z = np.dot(x1,x2)
print(x1, x2, z ,sep='\n')

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
[[1 2]
 [3 4]
 [5 6]]
[[ 22  28]
 [ 49  64]
 [ 76 100]
 [103 136]
 [130 172]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
x = np.random.randint(1,10,size=20)
x

array([7, 4, 6, 1, 7, 6, 2, 8, 5, 3, 5, 4, 6, 6, 9, 8, 3, 9, 5, 5])

In [ ]:
for i in range(x.size):
    if (x[i]>3 and x[i]<8): #3 and 8 are excluded
        x[i] = -(x[i])
print(x)

[-7 -4 -6  1 -7 -6  2  8 -5  3 -5 -4 -6 -6  9  8  3  9 -5 -5]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
z = np.array([1,2,3,4])

In [ ]:
z**z

array([  1,   4,  27, 256])

In [ ]:
2 << z >> 2

array([1, 2, 4, 8])

In [ ]:
z <- z

array([False, False, False, False])

In [ ]:
1j*z

array([0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])

In [ ]:
z/1/1

array([1., 2., 3., 4.])

In [ ]:
z < z >z

ValueError: ignored

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [ ]:
np.array(0) // np.array(0)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [ ]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
x = np.random.rand(10)

In [ ]:
np.ceil(x)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
np.intersect1d(a,b)

array([4, 5])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [5]:
old_setting= np.seterr(all="ignore")
Z = np.ones(1) / 0

In [6]:
_ = np.seterr(**old_setting)

In [7]:
with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
today = np.datetime64('today','D')
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
tomorrow =np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday, today, tomorrow)

2022-07-07 2022-07-08 2022-07-09


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
np.arange('2016-07','2016-08', dtype="datetime64[D]")

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
A = np.ones(5)*2
B = np.ones(5)
np.add(A, B, out=B)
np.negative(A, out=A)
np.divide(A,2, out=A)
np.multiply(A,B, out=A)
print(A)

[-3. -3. -3. -3. -3.]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
x = np.random.rand(5)

In [ ]:
x

array([0.71637844, 0.79848465, 0.4828398 , 0.90240988, 0.3325964 ])

In [ ]:
x - (x%1)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ceil(x)

array([1., 1., 1., 1., 1.])

In [ ]:
np.floor(x)

array([0., 0., 0., 0., 0.])

In [ ]:
x.astype(int)

array([0, 0, 0, 0, 0])

In [ ]:
np.trunc(x)

array([0., 0., 0., 0., 0.])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
x = np.arange(5)
np.tile(x,(5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
def generate():
    for x in range(10):
        yield x
x = np.fromiter(generate(),dtype=float)
print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
np.linspace(0,1,11,endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
x  = np.random.rand(10)
print(x)
np.sort(x)

[0.73427546 0.80061205 0.35924152 0.65410128 0.86831047 0.29030915
 0.1333098  0.41714531 0.9100809  0.6092167 ]


array([0.1333098 , 0.29030915, 0.35924152, 0.41714531, 0.6092167 ,
       0.65410128, 0.73427546, 0.80061205, 0.86831047, 0.9100809 ])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
x = np.array([1,2,3,4,5])
np.add.reduce(x)

15

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
A = np.random.randint(0,3,5)
B = np.random.randint(0,3,5)
np.allclose(A,B)

False

In [ ]:
np.array_equal(A,B)

False

#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
x = np.zeros(5)
x.flags.writeable = False

In [ ]:
x[1] = 1

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
a = np.random.random((10,2))
X,Y = a[:,0], a[:,1] # getting x and y coordinates seperately
radius = np.sqrt(X**2+Y**2)
theta = np.arctan2(Y,X)
print(radius)
print(theta)

[0.9213754  1.09126535 0.82900951 0.97677312 0.91559928 0.70571503
 0.44277028 0.93334075 0.52954584 1.07601116]
[1.04810284 0.56701885 1.54064364 0.9447853  0.45406741 1.16833729
 0.8086651  1.53676343 0.48330103 0.41909488]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
x = np.random.random(10)
x[x.argmax()] = 0
print(x)

[0.78942231 0.         0.38622893 0.30170481 0.36921378 0.9338586
 0.09607242 0.70789572 0.11889073 0.56504123]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
z = np.zeros((5,5), dtype=[('x', float), ('y', float)])
a = np.linspace(0,1,5)
b = np.linspace(0,1,5)
z['x'], z['y']= np.meshgrid(a,b)


In [ ]:
z

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
X = np.arange(5)
Y = np.ones(5)
C = 1.0 / np.subtract.outer(X, Y)
C

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([[-1.        , -1.        , -1.        , -1.        , -1.        ],
       [        inf,         inf,         inf,         inf,         inf],
       [ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ],
       [ 0.5       ,  0.5       ,  0.5       ,  0.5       ,  0.5       ],
       [ 0.33333333,  0.33333333,  0.33333333,  0.33333333,  0.33333333]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)
   

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
np.set_printoptions(threshold=float("inf"))
X = np.zeros((10,10))
print(X)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [11]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(v)
print(Z[index])

53.57787351354403
54


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
np.array([], dtype=[('position',[('x',np.int32), ('y',np.int32)]),
                     ('color', [('r', np.int32), ('g', np.int32),('b', np.int32)])])

array([],
      dtype=[('position', [('x', '<i4'), ('y', '<i4')]), ('color', [('r', '<i4'), ('g', '<i4'), ('b', '<i4')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [12]:
Z = np.random.random((100,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.24184167 0.34687801 ... 0.58795249 0.21363532 0.37206247]
 [0.24184167 0.         0.55602927 ... 0.38249515 0.09241779 0.46175357]
 [0.34687801 0.55602927 0.         ... 0.80319484 0.48686972 0.63437006]
 ...
 [0.58795249 0.38249515 0.80319484 ... 0.         0.37466527 0.83889561]
 [0.21363532 0.09241779 0.48686972 ... 0.37466527 0.         0.50747216]
 [0.37206247 0.46175357 0.63437006 ... 0.83889561 0.50747216 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
x = np.arange(10,dtype=np.float32)

In [ ]:
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [ ]:
y = x.astype(np.int32)

In [ ]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [13]:
from io import StringIO

data = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
X = np.genfromtxt(data, delimiter=",", dtype=np.int)
print(X)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  import sys


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
X = np.random.randint(1,11,(2,2))
for index, value in np.ndenumerate(X):
    print(index, value)
for index in np.ndindex(X.shape):
    print(index, X[index])

(0, 0) 6
(0, 1) 9
(1, 0) 1
(1, 1) 9
(0, 0) 6
(0, 1) 9
(1, 0) 1
(1, 1) 9


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
x, y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
d = np.sqrt(x*x+y*y)
sigma, mu = 1.0, 0.0
g = np.exp(-( (d-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(g)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
n = 5
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[1. 0. 0. 0. 0.]
 [1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
X = np.random.rand(4,5)
Y = X - X.mean(axis=1, keepdims=True)
Y

array([[ 0.36999027, -0.06937681, -0.14637222, -0.16482192,  0.01058068],
       [ 0.31693408, -0.19033469,  0.36308531, -0.22877724, -0.26090745],
       [ 0.08075857, -0.10728174,  0.10899834, -0.01229032, -0.07018485],
       [-0.11212951,  0.12875403, -0.29404381,  0.19950838,  0.07791091]])

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
x = np.random.randint(0,100,(3,3))
print(x)
x[x[:,1].argsort()]

[[93 49 87]
 [ 4 79 73]
 [ 6 75 52]]


array([[93, 49, 87],
       [ 6, 75, 52],
       [ 4, 79, 73]])

#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
x = np.random.randint(0,10,(4,5))
~x.any(axis=0).any()

False

#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
X = np.random.uniform(0,1,5)
value = 0.5
y = X.flat[np.abs(X-value).argmin()]
y

0.3735381729045625

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
print(A,B)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0]
 [1]
 [2]] [[0 1 2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
X = np.ones(10)
I = np.arange(len(X))
X += np.bincount(I)
X

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [ ]:
X = np.ones(10)
I = np.arange(len(X))
np.add.at(X, I, 1)
print(X)

[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [ ]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [ ]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(np.reshape(I, h*w*3))
n = len(colors)
print(n)

4


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [ ]:
X = np.arange(16).reshape(2,2,2,2)
X.sum(axis=(-2,-1))

array([[ 6, 22],
       [38, 54]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [14]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sum = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sum / D_counts
print(D_means)

[0.42029062 0.46581844 0.65474349 0.61459672 0.47204862 0.59513364
 0.63913856 0.51725177 0.45736578 0.54570824]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [ ]:
A = np.random.randint(1,5,(5,5))
B = np.random.randint(1,5,(5,5))
np.diag(np.dot(A, B))

array([36, 29, 31, 35, 33])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [ ]:
X = np.array([1,2,3,4,5])
num_zeros = 3
X_0 = np.zeros(len(X) + (len(X)-1)*(num_zeros))
X_0[::num_zeros+1] = X
print(X_0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [ ]:
A = np.ones((5,5,3))
B = np.ones((5,5))
print(A * B[:,:,None])

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
X = np.arange(25).reshape(5,5)
print(X)
X[[0,1]] = X[[1,0]]
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(C,np.bincount(A))

[0 2 1 1 2 0 1] [0 2 1 1 2 0 1]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [ ]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [ ]:
from numpy.lib import stride_tricks

def rolling_array(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling_array(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [ ]:
X = np.ones(10)
print(np.logical_not(X, out=X))

Y = np.random.uniform(-1.0,1.0,10)
print(Y)
print(np.negative(Y, out=Y))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.30444206 -0.1357446  -0.69007336 -0.9605445   0.93083524 -0.69573724
 -0.14399911 -0.63869497 -0.04933572  0.9257391 ]
[-0.30444206  0.1357446   0.69007336  0.9605445  -0.93083524  0.69573724
  0.14399911  0.63869497  0.04933572 -0.9257391 ]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [15]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 9.4342909  15.78987551  3.90526687  5.97100393  3.92599659  5.63807243
  4.53502368  3.5384924   8.74579238  0.45894628]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [16]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))
    
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[2.93567561e+00 4.42405380e+00 1.15031892e+01 1.06530387e+01
  6.83916581e-01 2.94025941e+00 3.13545922e-01 1.13692386e+01
  1.12995326e+01 4.01740246e+00]
 [8.58119109e+00 3.73404858e+00 8.84788893e+00 4.45906845e-01
  7.67325283e+00 2.22612543e+00 1.12248169e+01 1.54120639e+00
  8.83406431e+00 9.41360676e+00]
 [9.39270903e+00 5.30340473e+00 1.00746186e+01 1.09014368e-02
  1.04041770e+01 4.63390973e+00 1.41104732e+01 2.81879531e+00
  1.00952391e+01 8.71853901e+00]
 [6.20467289e+00 5.74426389e+00 9.88989837e-01 8.62126524e-01
  6.78816038e+00 1.09923240e+01 3.61356545e+00 3.31030856e+00
  8.10714826e-01 1.46939834e+01]
 [4.08486856e+00 4.27580808e+00 1.01225570e+01 4.47874003e+00
  4.77111059e+00 5.53154593e-01 7.32127414e+00 3.43725706e+00
  1.00381664e+01 7.12584553e+00]
 [1.01352669e+01 6.75325528e+00 1.12092101e+01 3.84705143e-01
  1.29213766e+01 6.85458700e+00 1.67690401e+01 3.99096872e+00
  1.12615291e+01 8.07332909e+00]
 [6.78292213e+00 8.52558789e+00 1.57728161e+01 1.47427750e

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
Z = np.arange(1,15,dtype=np.int32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [ ]:
Z = np.random.uniform(0,1,(10,10))

rank = np.linalg.matrix_rank(Z)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [ ]:
X = np.random.randint(0,10,50)
print(X)
print(np.bincount(X).argmax())

[6 5 2 1 6 4 4 1 9 2 3 0 2 3 6 7 1 4 7 1 7 6 0 0 7 7 9 8 7 7 4 0 5 8 2 5 6
 9 9 2 9 8 2 3 2 8 4 9 6 7]
7


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[3 4 3]
   [1 3 1]
   [3 4 0]]

  [[4 3 0]
   [3 1 3]
   [4 0 4]]

  [[3 0 0]
   [1 3 1]
   [0 4 0]]

  [[0 0 4]
   [3 1 1]
   [4 0 4]]

  [[0 4 1]
   [1 1 1]
   [0 4 0]]

  [[4 1 1]
   [1 1 2]
   [4 0 4]]

  [[1 1 0]
   [1 2 0]
   [0 4 4]]

  [[1 0 3]
   [2 0 3]
   [4 4 2]]]


 [[[1 3 1]
   [3 4 0]
   [4 4 2]]

  [[3 1 3]
   [4 0 4]
   [4 2 3]]

  [[1 3 1]
   [0 4 0]
   [2 3 1]]

  [[3 1 1]
   [4 0 4]
   [3 1 2]]

  [[1 1 1]
   [0 4 0]
   [1 2 2]]

  [[1 1 2]
   [4 0 4]
   [2 2 0]]

  [[1 2 0]
   [0 4 4]
   [2 0 0]]

  [[2 0 3]
   [4 4 2]
   [0 0 0]]]


 [[[3 4 0]
   [4 4 2]
   [2 1 1]]

  [[4 0 4]
   [4 2 3]
   [1 1 4]]

  [[0 4 0]
   [2 3 1]
   [1 4 2]]

  [[4 0 4]
   [3 1 2]
   [4 2 4]]

  [[0 4 0]
   [1 2 2]
   [2 4 3]]

  [[4 0 4]
   [2 2 0]
   [4 3 1]]

  [[0 4 4]
   [2 0 0]
   [3 1 0]]

  [[4 4 2]
   [0 0 0]
   [1 0 0]]]


 [[[4 4 2]
   [2 1 1]
   [4 4 1]]

  [[4 2 3]
   [1 1 4]
   [4 1 2]]

  [[2 3 1]
   [1 4 2]
   [1 2 3]]

  [[3 1 2]
   [4 2 4]
   [2 3 3]]

  [[1 2 2]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [ ]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S.shape)

(20, 1)


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [ ]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [ ]:
Z = np.arange(100)
np.random.shuffle(Z)
n = 5

print (Z[np.argsort(Z)[-n:]])

[95 96 97 98 99]


In [ ]:
print (Z[np.argpartition(-Z,n)[:n]])

[98 99 97 96 95]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [ ]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [20]:
Z = np.array([("Welcome", 7.4, 3),
              ("Home", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Welcome', 7.4, 3) (b'Home', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [ ]:
x = np.random.rand(int(5e5))
print(np.power(x,3))
print(x*x*x)
print(np.einsum('i,i,i->i',x,x,x))

[3.38823673e-01 4.84034589e-02 8.31884475e-01 ... 2.46822554e-01
 4.14258286e-01 1.59307510e-04]
[3.38823673e-01 4.84034589e-02 8.31884475e-01 ... 2.46822554e-01
 4.14258286e-01 1.59307510e-04]
[3.38823673e-01 4.84034589e-02 8.31884475e-01 ... 2.46822554e-01
 4.14258286e-01 1.59307510e-04]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
print(A,B,sep='\n')
C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[[2 3 1]
 [2 0 0]
 [0 4 1]
 [2 1 0]
 [2 0 4]
 [2 3 4]
 [1 2 2]
 [0 4 0]]
[[2 2]
 [0 1]]
[0 1 3 4 6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [ ]:
Z = np.random.randint(0,5,(10,3))
print(Z)

E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

[[3 4 2]
 [1 2 0]
 [1 0 4]
 [4 3 0]
 [1 0 1]
 [4 3 0]
 [3 3 3]
 [1 3 3]
 [4 1 4]
 [3 2 3]]
[[3 4 2]
 [1 2 0]
 [1 0 4]
 [4 3 0]
 [1 0 1]
 [4 3 0]
 [1 3 3]
 [4 1 4]
 [3 2 3]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [ ]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [ ]:
X = np.array([[1,2,3],[1,2,3],[1,2,3],[4,5,6],[7,8,9]])
print(X)
unique_rows = np.unique(X, axis=0)
print(unique_rows)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [ ]:
#A = np.random.uniform(0,1,10)
#B = np.random.uniform(0,1,10)
A = 2*np.ones(5)
B = 3*np.ones(5)
print(A)
print(B)
print("Sum", np.einsum('i->', A))      # np.sum(A)
print("Product",np.einsum('i,i->i', A, B)) # A * B
print("Inner",np.einsum('i,i', A, B))   # np.inner(A, B)
print("Outer",np.einsum('i,j->ij', A, B))    # np.outer(A, B)

[2. 2. 2. 2. 2.]
[3. 3. 3. 3. 3.]
Sum 10.0
Product [6. 6. 6. 6. 6.]
Inner 30.0
Outer [[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [ ]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [21]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [23]:
X = np.random.randn(100)
N = 1000 # number of samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confidence = np.percentile(means, [5, 95])
print(confidence)

[-0.25151119  0.07623918]
